If installed, prefer the ueberdosis/pandoc package over ryakad/pandoc-php
renanbr/bibtex-parser pull request #108
Opened 2023-07-13 20:06 UTC by extracts

This pull request presents a possible solution for renanbr/bibtex-parser#107, i.e. it will cause the [ueberdosis/pandoc](https://packagist.org/packages/ueberdosis/pandoc) package to be preferred over [ryakad/pandoc-php](https://packagist.org/packages/ryakad/pandoc-php) if it is installed.

2023-07-14 11:01 UTC, renanbr requested changes

2023-07-14 11:01 UTC, renanbr commented on src/Processor/LatexToUnicodeProcessor.php
> +            }
Some suggestions:

- Checking if a package is installed or not should be done once, during the converter creation, not every time this processor is called
- We could wrap pandoc initialisation inside a callable
  - signature: `function (string $latex): string`
  - then we can rename `->pandoc` attribute to `->converter`
- We need tests with both libraries, we may need:
  - remove `ryakad/pandoc-php` as dev dependency
  - add them dynamically when running the CI
  - throw proper exception when none is installed

2023-08-21 20:18 UTC, renanbr approved these changes

2023-08-21 20:19 UTC, renanbr commented
@extracts I pushed 2a90df52692bd5172f86dfe6259db913d06c45f0 with CI, CS and PHPStan fixes.

Let me know if the current keep the library working for your use case.

2023-08-23 10:29 UTC, extracts commented
@renanbr Thanks for the fixes, I've tested the changes in this pull request with our software and can report that it all works fine.

2023-08-25 11:21 UTC, merged